export const data = [
    {
        id: 1,
        name: "Cozy Place",
        price: 1500,
        dimensions: 43,
        no_of_people:'2-6',
        guests:'6',
        rooms:"2",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2014/07/10/17/17/hotel-389256__340.jpg'
    },
    {
        id: 2,
        name: "Bright Suite",
        price: 5000,
        dimensions: 100,
        no_of_people:'4-8',
        guests:'8',
        rooms:"1",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2018/02/24/17/17/window-3178666__340.jpg'
    },
    {
        id: 3,
        name: "James Abode",
        price: 1005,
        dimensions: 43,
        no_of_people:'2-4',
        guests:'4',
        rooms:"1",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2020/02/01/06/12/living-room-4809587__480.jpg'
    },
    {
        id: 4,
        name: "Hyatt",
        price: 9050,
        dimensions: 50,
        no_of_people:'1-4',
        guests:'4',
        rooms:"1",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2021/11/08/00/30/living-room-6778197__480.jpg'
    },
    {
        id: 5,
        name: "Holiday Inn",
        price: 1030,
        dimensions: 60,
        no_of_people:'4-6',
        guests:'6',
        rooms:"2",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2019/06/13/17/08/round-window-4272049__480.jpg'
    },
    {
        id: 6,
        name: "Maria's Home",
        price: 6022,
        dimensions: 70,
        no_of_people:'3-7',
        guests:'7',
        rooms:"2",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque, beatae. Nemo, odio similique. Officia ab voluptas voluptatem, necessitatibus tempore eum!",
        image: 'https://cdn.pixabay.com/photo/2016/04/15/11/45/hotel-1330841__480.jpg'
    },
    {
        id: 7,
        name: "New Modern",
        price: 1500,
        dimensions: 43,
        guests:'1',
        rooms:"2",
        no_of_people:'2-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-1.jpg')
    },
    {
        id: 8,
        name: "Dazzling Home",
        price: 5000,
        guests:'1',
        rooms:"2",
        dimensions: 100,
        no_of_people:'4-8',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-2.jpg')
    },
    {
        id: 9,
        name: "Orange Suites",
        price: 1050,
        guests:'3',
        rooms:"3",
        dimensions: 43,
        no_of_people:'2-4',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-3.jpg')
    },
    {
        id: 10,
        name: "Central Apt.",
        price: 9500,
        guests:'3',
        rooms:"4",
        dimensions: 50,
        no_of_people:'1-4',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-4.jpg')
    },
    {
        id: 11,
        name: "La Casa di Egisto",
        price: 1003,
        guests:'6',
        rooms:"4",
        dimensions: 60,
        no_of_people:'4-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-5.jpg')
    },
    {
        id: 12,
        name: "Emma’s Rooms",
        price: 6200,
        guests:'5',
        rooms:"3",
        dimensions: 70,
        no_of_people:'3-7',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-6.jpg')
    },
    {
        id: 13,
        name: "Villa Laura",
        price: 1003,
        guests:'5',
        rooms:"3",
        dimensions: 60,
        no_of_people:'4-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-7.jpg')
    },
    {
        id: 14,
        name: "Maisonette",
        price: 1330,
        guests:'4',
        rooms:"3",
        dimensions: 60,
        no_of_people:'4-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-8.jpg')
    },
    {
        id: 15,
        name: "Artistic Loft",
        price: 4503,
        guests:'6',
        rooms:"1",
        dimensions: 60,
        no_of_people:'4-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-9.jpg'),
    },
    {
        id: 16,
        name: "Casa Mancini",
        price: 6103,
        guests:'5',
        rooms:"2",
        dimensions: 60,
        no_of_people:'4-6',
        description: "Ut et rhoncus odio. Quisque pellentesque nisl leo, eget ultricies nibh ullamcorper ut. Curabitur bibendum sed neque quis rhoncus maecenas",
        image: require('./components/Rooms/Roomimages/room-featured-img-10.jpg')
    }
]